Add-Type -AssemblyName System.Drawing
$bmp1 = New-Object System.Drawing.Bitmap(192, 192)
$g1 = [System.Drawing.Graphics]::FromImage($bmp1)
$g1.Clear([System.Drawing.Color]::Blue)
$font = New-Object System.Drawing.Font("Arial", 48)
$brush = New-Object System.Drawing.SolidBrush([System.Drawing.Color]::White)
$g1.DrawString("WMS", $font, $brush, 10, 60)
$bmp1.Save("c:\Project\Scanner\Scanner\wwwroot\icon-192.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp1.Dispose()
$g1.Dispose()

$bmp2 = New-Object System.Drawing.Bitmap(512, 512)
$g2 = [System.Drawing.Graphics]::FromImage($bmp2)
$g2.Clear([System.Drawing.Color]::Blue)
$font2 = New-Object System.Drawing.Font("Arial", 128)
$g2.DrawString("WMS", $font2, $brush, 20, 160)
$bmp2.Save("c:\Project\Scanner\Scanner\wwwroot\icon-512.png", [System.Drawing.Imaging.ImageFormat]::Png)
$bmp2.Dispose()
$g2.Dispose()
$brush.Dispose()
$font.Dispose()
$font2.Dispose()
